version: 2
updates:
  - package-ecosystem: "bundler"
    directory: "/"
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: "webrick"
      - dependency-name: "addressable"
      - dependency-name: "rexml"
      - dependency-name: "google-protobuf"
